---
- name: installing selinux dependecy
  yum:
    name: libselinux-python
    state: latest

- name: change selinux policy
  selinux:
    state: permissive

- command: setenforce 0

- command: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux

- name: making entries in bridge-nf-call-iptables file
  lineinfile:
    path: /proc/sys/net/bridge/bridge-nf-call-iptables
    state: present
    line: '1'

- name: making entries in kubernetes repo file
  blockinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    state: present
    create: yes
    insertafter: EOF
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=http://10.10.60.169/kubernetes/
      enabled=1
      gpgcheck=0

- name: Installing Packages
  yum:
    name: ['kubeadm', 'docker', 'firewalld']
    state: latest

- name: configuring docker file to use ip address
  lineinfile:
    path: /etc/sysconfig/docker
    regexp: '^OPTIONS'
    line: "OPTIONS='--selinux-enabled --insecure-registry={{ ansible_all_ipv4_addresses[0] }}:5000--log-driver=journald --signature-verification=false'"

- name: Enabling firewalld ports
  firewalld:
    port: ['10250/tcp', '10255/tcp', '30000-32767/tcp', '6783/tcp']
    permanent: true
    state: enabled

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: restarting and enabling docker service
  service:
    name: docker
    enabled: yes
    state: restarted
